spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/emfo
    username: root
    password: emfo!@0717
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: false
        use_sql_comments: false
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full
            connectTimeout: 5000
            readTimeout: 5000
      multipart:
        enabled: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  task:
    scheduling:
      pool:
        size: 5


logging:
  level:
    root: INFO
    #feign: DEBUG
    #org.springframework.cloud.openfeign: DEBUG
    #org.springframework.web.client.RestTemplate: DEBUG
    org.hibernate.SQL: off
    org.hibernate.type: off

server:
  domain: http://mydomain.com
  username: emfoplus_kpro
  password: emfo!@0717